extends:
  - eslint-config-dmitmel/presets/node
  - eslint-config-dmitmel/presets/formatting
env:
  browser: true
parser: babel-eslint
parserOptions:
  sourceType: module
overrides:
  - files: ./src/**/*.js
    rules:
      node/no-unsupported-features/es-syntax: off
  - files: ./webpack.config.js
    rules:
      node/no-unpublished-require: off
